### ISSUE TITLE
Integration not showing countries nor banks, crashing

### ISSUE THREAD

**Issue by SerggioC** [getkevin/kevin-ios#74]
I'm setting bank payment with:

```
                        KevinPaymentSession.shared.delegate = self
                        // initialize configuration with paymentID fetched from the API
                        let configuration = try KevinPaymentSessionConfiguration.Builder(paymentId: paymentID)
                            .setPaymentType(.bank)
                            .setPreselectedCountry(KevinCountry.portugal)
                            .setDisableCountrySelection(false)
                            .setSkipBankSelection(false)
                            .setSkipAuthentication(false)
                            .build()
                        KevinPaymentSession.shared.initiatePayment(configuration: configuration)
```

App crashes If I continue

![bug1](https://user-images.githubusercontent.com/21109275/227500316-0d370564-5149-4bb5-ba3e-1dfb9e4d14b7.png)
![bug2](https://user-images.githubusercontent.com/21109275/227500321-dac1e289-5904-4b6b-9932-94c6812af5cb.png)

**Comment by typuk** [comment]
Hi @SerggioC,

Thank you for reaching out. May I ask you to provide crash log or at least the point of crash or error message? That would significantly simplify identifying issues for us.

Cheers Arturs

**Comment by SerggioC** [comment]
Hi @typuk,
Thanks for reply.

The error is at this function because selectedBankId is nil at this point. 
From file KevinBankSelectionView line 142.

```
    @objc func onContinueClicked(_ sender: UIButton) {
        delegate?.invokeContinuation(bankId: selectedBankId)
    }
```

Using Kevin version 2.2.9 as Package dependency in Xcode.
Any ideas why we don't get any countries or banks to select?


Thank you.

**Comment by typuk** [comment]
Hello, again @SerggioC 

As I can see it could be either one of the issues. 
1. `paymentID` is incorrect. `paymentID` is used for authentificating endoints, so if it is invalid we fail to load list of banks. Maybe you are using Sandbox by anychance? If that is the case you need to set `Kevin.shared.isSandbox = true`
2. Issues with internet connection. Might be simple connectivity issues.

In any case, we will register ticket for imporving networking to handle those scenarios more gracefully. 

Let me know if this helps.

Cheers

**Comment by SerggioC** [comment]
Hi @typuk,

It was the paymentID that I reused from the android sample, it should have some validity I suppose.  
It shows the countries and the bank list using new paymentID.
Setting `Kevin.shared.isSandbox = true` does not work. What is it supposed to do? There's no information in the documentation.

I'm not using the paymentID from my backend for now, this is just the first tests. 
Is there a general paymentID we can use for this tests?


Thank you.

**Comment by typuk** [comment]
Hello again, 

I have fixed our Demo app and test payments should work now!

You can check our [documentation](https://developer.kevin.eu/home/mobile-sdk/backend/payment-initiation) on how to generate paymentId. For testing purposes you should use testing keys, that will allow you to use testing banks. 

I hope this clarifies things somewhat.
